# Generated by Django 5.2.5 on 2025-10-22 16:13

from django.db import migrations

def create_joseph_profile(apps, schema_editor):
    Profile = apps.get_model('showcase', 'Profile')
    Profile.objects.create(
        name='Joseph Ombati',
        role='Creative Technologist & Animator',
        location='Nairobi, Kenya',
        tagline='Cinematic storytelling meets technical mastery — blending Blender, Mixamo, and Python automation.'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_joseph_profile),
    ]
